device: cpu
latent_encoding_mode: offline

data:
  num_samples: 6
  num_protein_atoms: 3
  num_ligand_atoms: 2
  protein_atom_feature_dim: 4
  ligand_atom_feature_dim: 4

encode:
  batch_size: 2

model:
  hidden_dim: 16
  z_shared_dim: 4
  z_pi_dim: 2
  property_names: ["affinity", "qed"]

  num_layers: 1
  edge_feat_dim: 4
  num_r_gaussian: 20
  knn: 2
  r_max: 5.0
  cutoff_mode: knn
  act_fn: silu
  norm: false
  update_x: false
  enable_correlation_matrix: false

train:
  seed: 123

